-- =============================================================================
-- CodeAlpha E-Commerce Store — Product Catalog Expansion
-- =============================================================================
USE `codealpha_ecommerce`;

-- 1. Add new categories
INSERT IGNORE INTO `categories` (`id`, `name`, `slug`, `description`) VALUES
  (6, 'Beauty', 'beauty', 'Skincare, makeup, and personal care products.'),
  (7, 'Accessories', 'accessories', 'Bags, wallets, belts, and tech accessories.');

-- 2. Add realistic products
INSERT IGNORE INTO `products` (`category_id`, `name`, `slug`, `description`, `image_url`, `price`, `stock`, `is_featured`) VALUES
  (1, 'Google Pixel 8 Pro', 'google-pixel-8-pro', 'Google''s flagship phone with advanced AI cameras.', 'https://picsum.photos/seed/google-pixel-8-pro/600/600', 999.0, 130, 1),
  (1, 'OnePlus 12', 'oneplus-12', 'Flagship killer with Snapdragon 8 Gen 3 and fast charging.', 'https://picsum.photos/seed/oneplus-12/600/600', 799.99, 68, 0),
  (1, 'Dell XPS 15', 'dell-xps-15', 'Premium 15-inch laptop with OLED display and powerful performance.', 'https://picsum.photos/seed/dell-xps-15/600/600', 1899.0, 130, 0),
  (1, 'HP Spectre x360', 'hp-spectre-x360', 'Versatile 2-in-1 laptop with stunning design and battery life.', 'https://picsum.photos/seed/hp-spectre-x360/600/600', 1499.5, 138, 1),
  (1, 'Lenovo ThinkPad X1 Carbon', 'lenovo-thinkpad-x1', 'Business ultrabook with top-tier keyboard and lightweight build.', 'https://picsum.photos/seed/lenovo-thinkpad-x1/600/600', 1600.0, 144, 0),
  (1, 'JBL Charge 5', 'jbl-charge-5', 'Portable Bluetooth speaker with deep bass and waterproof design.', 'https://picsum.photos/seed/jbl-charge-5/600/600', 149.95, 42, 0),
  (1, 'Apple Watch Series 9', 'apple-watch-series-9', 'Advanced health tracking, double tap gesture, and bright display.', 'https://picsum.photos/seed/apple-watch-series-9/600/600', 399.0, 119, 0),
  (1, 'Logitech MX Master 3S', 'logitech-mx-master-3s', 'Ergonomic wireless mouse tailored for creators and coders.', 'https://picsum.photos/seed/logitech-mx-master-3s/600/600', 99.99, 38, 0),
  (1, 'Keychron Q1 Pro', 'keychron-q1-pro', 'Wireless custom mechanical keyboard with aluminum body.', 'https://picsum.photos/seed/keychron-q1-pro/600/600', 199.0, 56, 0),
  (1, 'Logitech Brio 4K Webcam', 'logitech-brio-4k', 'Ultra HD webcam for professional video calls and streaming.', 'https://picsum.photos/seed/logitech-brio-4k/600/600', 169.99, 98, 0),
  (1, 'Samsung 990 PRO 2TB SSD', 'samsung-990-pro-2tb', 'Blazing fast PCIe 4.0 NVMe SSD for gaming and intensive tasks.', 'https://picsum.photos/seed/samsung-990-pro-2tb/600/600', 189.99, 63, 0),
  (1, 'Asus ROG Zephyrus G14', 'asus-rog-zephyrus-g14', 'Powerful and portable 14-inch gaming laptop.', 'https://picsum.photos/seed/asus-rog-zephyrus-g14/600/600', 1449.99, 142, 0),
  (1, 'Sony A7 IV Mirrorless Camera', 'sony-a7-iv', 'Hybrid full-frame camera perfect for photos and video.', 'https://picsum.photos/seed/sony-a7-iv/600/600', 2498.0, 99, 0),
  (1, 'Nintendo Switch OLED', 'nintendo-switch-oled', 'Handheld console with a vibrant OLED screen.', 'https://picsum.photos/seed/nintendo-switch-oled/600/600', 349.99, 100, 1),
  (1, 'Bose QuietComfort Ultra', 'bose-qc-ultra', 'Premium noise-cancelling headphones with immersive spatial audio.', 'https://picsum.photos/seed/bose-qc-ultra/600/600', 429.0, 95, 0),
  (2, 'Men''s Classic T-Shirt', 'mens-classic-tshirt', '100% cotton crewneck t-shirt. Everyday essential.', 'https://picsum.photos/seed/mens-classic-tshirt/600/600', 25.0, 46, 1),
  (2, 'Women''s Summer Dress', 'womens-summer-dress', 'Light and breezy floral dress perfect for warm weather.', 'https://picsum.photos/seed/womens-summer-dress/600/600', 45.0, 107, 0),
  (2, 'Slim Fit Jeans', 'slim-fit-jeans', 'Comfortable stretch denim in a modern slim fit.', 'https://picsum.photos/seed/slim-fit-jeans/600/600', 55.0, 150, 0),
  (2, 'Fleece Pullover Hoodie', 'fleece-pullover-hoodie', 'Cozy fleece hoodie with kangaroo pocket.', 'https://picsum.photos/seed/fleece-pullover-hoodie/600/600', 40.0, 81, 0),
  (2, 'Chuck Taylor All Star', 'chuck-taylor-all-star', 'The classic canvas sneaker that goes with everything.', 'https://picsum.photos/seed/chuck-taylor-all-star/600/600', 60.0, 102, 0),
  (2, 'Leather Biker Jacket', 'leather-biker-jacket', 'Genuine leather jacket with asymmetrical zip closure.', 'https://picsum.photos/seed/leather-biker-jacket/600/600', 199.99, 117, 1),
  (2, 'Casio Vintage Watch', 'casio-vintage-watch', 'Retro digital watch with stainless steel band.', 'https://picsum.photos/seed/casio-vintage-watch/600/600', 35.0, 101, 0),
  (2, 'Polarized Sunglasses', 'polarized-sunglasses', 'UV400 protection with durable lightweight frames.', 'https://picsum.photos/seed/polarized-sunglasses/600/600', 29.99, 89, 0),
  (2, 'Designer Tote Handbag', 'designer-tote-handbag', 'Spacious and elegant tote bag crafted from vegan leather.', 'https://picsum.photos/seed/designer-tote-handbag/600/600', 89.99, 84, 1),
  (2, 'Running Sports Shoes', 'running-sports-shoes', 'Lightweight athletic shoes with breathable mesh.', 'https://picsum.photos/seed/running-sports-shoes/600/600', 75.0, 88, 1),
  (2, 'Men''s Chino Pants', 'mens-chino-pants', 'Versatile flat-front chinos for casual or office wear.', 'https://picsum.photos/seed/mens-chino-pants/600/600', 49.99, 66, 0),
  (2, 'Winter Puffer Coat', 'winter-puffer-coat', 'Warm, insulated coat to brave the cold months.', 'https://picsum.photos/seed/winter-puffer-coat/600/600', 120.0, 47, 1),
  (3, 'The AI Revolution in Medicine', 'ai-revolution-medicine', 'How AI is transforming healthcare and saving lives.', 'https://picsum.photos/seed/ai-revolution-medicine/600/600', 28.0, 99, 0),
  (3, 'Machine Learning Yearning', 'ml-yearning', 'A practical guide to structuring machine learning projects.', 'https://picsum.photos/seed/ml-yearning/600/600', 35.0, 30, 0),
  (3, 'Zero to One', 'zero-to-one', 'Notes on startups, or how to build the future.', 'https://picsum.photos/seed/zero-to-one/600/600', 22.0, 143, 0),
  (3, 'Thinking, Fast and Slow', 'thinking-fast-and-slow', 'Groundbreaking tour of the mind and decision making.', 'https://picsum.photos/seed/thinking-fast-and-slow/600/600', 19.99, 120, 0),
  (3, 'Dune by Frank Herbert', 'dune-frank-herbert', 'The epic masterpiece of science fiction.', 'https://picsum.photos/seed/dune-frank-herbert/600/600', 18.5, 118, 0),
  (3, 'Sapiens: A Brief History of Humankind', 'sapiens', 'Exploring the history and impact of Homo sapiens.', 'https://picsum.photos/seed/sapiens/600/600', 24.99, 68, 0),
  (3, 'A Brief History of Time', 'brief-history-of-time', 'Stephen Hawking''s classic work on cosmology.', 'https://picsum.photos/seed/brief-history-of-time/600/600', 18.0, 29, 0),
  (3, 'Rich Dad Poor Dad', 'rich-dad-poor-dad', 'What the rich teach their kids about money.', 'https://picsum.photos/seed/rich-dad-poor-dad/600/600', 16.95, 125, 0),
  (3, 'Project Hail Mary', 'project-hail-mary', 'A lone astronaut must save the earth from disaster.', 'https://picsum.photos/seed/project-hail-mary/600/600', 20.0, 63, 0),
  (3, 'Grokking Algorithms', 'grokking-algorithms', 'An illustrated guide for programmers and other curious people.', 'https://picsum.photos/seed/grokking-algorithms/600/600', 39.99, 100, 0),
  (4, 'KitchenAid Stand Mixer', 'kitchenaid-stand-mixer', 'Iconic stand mixer for baking and food prep.', 'https://picsum.photos/seed/kitchenaid-stand-mixer/600/600', 379.99, 74, 0),
  (4, 'Zojirushi Rice Cooker', 'zojirushi-rice-cooker', 'Micom rice cooker and warmer for perfect rice every time.', 'https://picsum.photos/seed/zojirushi-rice-cooker/600/600', 145.0, 110, 0),
  (4, 'Yeti Rambler 20 oz', 'yeti-rambler-20', 'Stainless steel vacuum insulated tumbler.', 'https://picsum.photos/seed/yeti-rambler-20/600/600', 35.0, 142, 0),
  (4, 'Ergonomic Office Chair', 'ergonomic-office-chair', 'Adjustable mesh chair with lumbar support.', 'https://picsum.photos/seed/ergonomic-office-chair/600/600', 199.99, 27, 0),
  (4, 'Modern Table Lamp', 'modern-table-lamp', 'Minimalist touch-control desk lamp with USB port.', 'https://picsum.photos/seed/modern-table-lamp/600/600', 39.99, 78, 0),
  (4, 'Shark Navigator Upright Vacuum', 'shark-navigator', 'Powerful upright vacuum with lift-away functionality.', 'https://picsum.photos/seed/shark-navigator/600/600', 159.99, 97, 0),
  (4, 'Caraway Nonstick Cookware', 'caraway-cookware', 'Ceramic non-stick 7-piece pot and pan set.', 'https://picsum.photos/seed/caraway-cookware/600/600', 395.0, 48, 0),
  (4, 'Corelle 18-Piece Dinner Set', 'corelle-dinner-set', 'Chip-resistant glass dinnerware set for 6.', 'https://picsum.photos/seed/corelle-dinner-set/600/600', 65.0, 102, 0),
  (4, 'Airtight Food Storage Containers', 'airtight-storage-containers', '7-piece BPA-free clear plastic pantry organization set.', 'https://picsum.photos/seed/airtight-storage-containers/600/600', 39.99, 47, 0),
  (4, 'Breville Barista Express', 'breville-barista-express', 'Create great tasting espresso in less than a minute.', 'https://picsum.photos/seed/breville-barista-express/600/600', 699.95, 32, 0),
  (5, 'Kookaburra Cricket Bat', 'kookaburra-cricket-bat', 'Premium English willow cricket bat for professional play.', 'https://picsum.photos/seed/kookaburra-cricket-bat/600/600', 199.99, 37, 0),
  (5, 'Adidas Fevernova Football', 'adidas-fevernova', 'Size 5 match ball inspired by classic designs.', 'https://picsum.photos/seed/adidas-fevernova/600/600', 39.99, 49, 0),
  (5, 'Spalding NBA Basketball', 'spalding-nba-basketball', 'Indoor/outdoor composite leather basketball.', 'https://picsum.photos/seed/spalding-nba-basketball/600/600', 49.99, 30, 0),
  (5, 'Yonex Astrox Badminton Racket', 'yonex-astrox', 'Lightweight graphite racket for smash power.', 'https://picsum.photos/seed/yonex-astrox/600/600', 85.0, 49, 0),
  (5, 'Under Armour Gym Bag', 'ua-gym-bag', 'Durable duffel bag with water-resistant finish.', 'https://picsum.photos/seed/ua-gym-bag/600/600', 45.0, 70, 0),
  (5, 'Everlast Skipping Rope', 'everlast-skipping-rope', 'Adjustable speed rope for cardio training.', 'https://picsum.photos/seed/everlast-skipping-rope/600/600', 12.99, 49, 1),
  (5, 'Manduka PRO Yoga Mat', 'manduka-pro-yoga-mat', 'Ultra-dense and spacious performance yoga mat.', 'https://picsum.photos/seed/manduka-pro-yoga-mat/600/600', 130.0, 96, 0),
  (5, 'Hex Dumbbell Set', 'hex-dumbbell-set-10-30', 'Rubber encased hex dumbbell sets (10-30 lbs).', 'https://picsum.photos/seed/hex-dumbbell-set-10-30/600/600', 150.0, 34, 0),
  (6, 'CeraVe Hydrating Face Wash', 'cerave-hydrating-cleanser', 'Gentle cleanser with ceramides and hyaluronic acid.', 'https://picsum.photos/seed/cerave-hydrating-cleanser/600/600', 15.99, 91, 0),
  (6, 'Olaplex No. 4 Shampoo', 'olaplex-no-4', 'Bond maintenance shampoo for healthier hair.', 'https://picsum.photos/seed/olaplex-no-4/600/600', 30.0, 116, 0),
  (6, 'Dior Sauvage Eau de Parfum', 'dior-sauvage-edp', 'A radically fresh and powerful men''s fragrance.', 'https://picsum.photos/seed/dior-sauvage-edp/600/600', 120.0, 33, 0),
  (6, 'MAC Matte Lipstick', 'mac-matte-lipstick', 'Iconic long-wearing matte finish lipstick.', 'https://picsum.photos/seed/mac-matte-lipstick/600/600', 23.0, 133, 0),
  (6, 'Cetaphil Moisturizing Cream', 'cetaphil-body-lotion', 'Rich body cream for ultimate hydration.', 'https://picsum.photos/seed/cetaphil-body-lotion/600/600', 17.5, 68, 1),
  (6, 'Dyson Supersonic Hair Dryer', 'dyson-supersonic', 'Fast drying with heat shield technology.', 'https://picsum.photos/seed/dyson-supersonic/600/600', 429.99, 46, 0),
  (6, 'La Mer Crème de la Mer', 'la-mer-face-cream', 'Luxurious and deeply moisturizing face cream.', 'https://picsum.photos/seed/la-mer-face-cream/600/600', 380.0, 36, 0),
  (6, 'Philips Norelco Multigroom', 'philips-multigroom', 'All-in-one trimmer for face, head, and body.', 'https://picsum.photos/seed/philips-multigroom/600/600', 59.95, 32, 0),
  (7, 'The North Face Backpack', 'north-face-backpack', 'Durable everyday backpack with laptop sleeve.', 'https://picsum.photos/seed/north-face-backpack/600/600', 89.0, 27, 0),
  (7, 'Bellroy Slim Leather Wallet', 'bellroy-slim-wallet', 'Minimalist front-pocket wallet blocking RFID.', 'https://picsum.photos/seed/bellroy-slim-wallet/600/600', 79.99, 114, 0),
  (7, 'Spigen iPhone 15 Case', 'spigen-iphone-15-case', 'Tough armor case with kickstand and drop protection.', 'https://picsum.photos/seed/spigen-iphone-15-case/600/600', 19.99, 20, 0),
  (7, 'Anker USB-C Hub 7-in-1', 'anker-usb-c-hub', 'Portable dock with 4K HDMI, SD card reader, and USB ports.', 'https://picsum.photos/seed/anker-usb-c-hub/600/600', 34.99, 94, 0),
  (7, 'Anker PowerCore 20000mAh', 'anker-power-bank', 'High-capacity portable charger with fast charging.', 'https://picsum.photos/seed/anker-power-bank/600/600', 49.99, 110, 0),
  (7, 'Anker Nylon USB-C Cable', 'anker-usb-c-cable', '6ft braided charging cable engineered for durability.', 'https://picsum.photos/seed/anker-usb-c-cable/600/600', 14.99, 89, 0),
  (7, 'TP-Link Bluetooth 5.0 Adapter', 'tp-link-bluetooth-adapter', 'Nano USB receiver for PC and laptops.', 'https://picsum.photos/seed/tp-link-bluetooth-adapter/600/600', 12.99, 134, 0);
